### PR TITLE
Address JB's comment on international perspective

### PR DESCRIPTION
**Pull request by awkawk**

### CODE REVIEW

**Comment by shawna-slh** [comment]
Suggestion for simpler coverage of the pertinent issues:
"Low vision" refers to visual impairments other than blindness. Other terms, such as "partially sighted" and "sight impaired", are used in different contexts. Some governments and organizations such as WHO define categories of low vision based on specific levels of visual acuity and field of vision. Visual acuity is the clarity or sharpness of vision. Field of vision is the area a person can see when their eyes are fixed in one position.

**Comment by allanj-uaag** [comment]
I like the simpler language. Adding low vision unrelated to any specific legal definition. Seems a useful thing to prevent confusion with governments and WHO.

"Low vision" refers to visual impairments other than blindness. Other terms, such as "partially sighted" and "sight impaired", are used in different contexts. Some governments and organizations such as WHO define categories of low vision based on specific levels of visual acuity and field of vision. Visual acuity is the clarity or sharpness of vision. Field of vision is the area a person can see when their eyes are fixed in one position. This document's reference to low vision is not connected to any specific legal definition.

**Comment by awkawk** [comment]
We shouldn't close pull requests when they are open in a survey.

**Comment by allanj-uaag** [comment]
thanks was just researching how to reopen. hit wrong button. Apologies

**Comment by shawna-slh** [comment]
Jim - I'm inclined to think that we don't need to add that additional sentence there, because of what we say in the rest of the section -- see: http://w3c.github.io/low-vision-a11y-tf/requirements.html#overview-of-low-vision
including "In considering user needs, this document uses a broad scope of low vision to include all visual impairments except significant blindness..."

**Comment by shawna-slh** [comment]
Jim in 10 Feb telecon "I'm OK with not adding that extra sentence"

**Comment by shawna-slh** [comment]
RESOLUTION 10 Feb telecon https://www.w3.org/2016/02/10-lvtf-minutes.html#item03

**Pull request closed without merging**
