### PR TITLE
Change to focus on ICT more broadly

### PR DESCRIPTION
**Pull request by awkawk**

### CODE REVIEW

**Comment by shawna-slh** [comment]
I think we can go with simply:
Accessibility Requirements for People with Low Vision describes what people with low vision need for electronic content, tools, and technologies to be accessible.

Or possibly:
Accessibility Requirements for People with Low Vision describes what people with low vision need for electronic content, tools, and technologies to be accessible — including information and communication technologies (ICT) such web content, web tools, non-web documents, and software.

**Comment by shawna-slh** [comment]
About the last edit:
The first paragraph talks about user needs. The second paragraph talks about requirements.

So I suggest leaving the first paragraph as is: "…It includes an overview of low vision and describes specific user needs. It does not set priorities on issues." And putting the 'not technical requirements' in the next paragraph: "User needs can be met at several levels, including hardware, operating systems, user agents (such as web browsers), extensions, plug-ins, assistive technologies, and content. This document does not specify responsibility for meeting user needs nor set technical requirements."

**Comment by allanj-uaag** [comment]
so final wording is...

Accessibility Requirements for People with Low Vision describes what people
with low vision need for web content, tools, and technologies to be
accessible. It includes an overview of low vision and describes specific
user needs. It does not set priorities on issues.

User needs can be met at several levels, including hardware, operating
systems, user agents (such as web browsers), extensions, plug-ins,
assistive technologies, and content. This document does not specify
responsibility for meeting user needs nor set technical requirements.

Additional information is available from Accessibility for People with Low
Vision https://www.w3.org/WAI/users/low-vision/.

On Mon, Feb 8, 2016 at 11:41 AM, shawn_slh notifications@github.com wrote:

> About the last edit:
> The first paragraph talks about user needs. The second paragraph talks
> about requirements.
> 
> So I suggest leaving the first paragraph as is: "…It includes an overview
> of low vision and describes specific user needs. It does not set priorities
> on issues." And putting the 'not technical requirements' in the next
> paragraph: "User needs can be met at several levels, including hardware,
> operating systems, user agents (such as web browsers), extensions,
> plug-ins, assistive technologies, and content. This document does not
> specify responsibility for meeting user needs nor set technical
> requirements."
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/pull/9#issuecomment-181436998.

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964

**Comment by shawna-slh** [comment]
Close but web->electronic. And with a minor grammar edit at the end:

Abstract:
Accessibility Requirements for People with Low Vision describes what people with low vision need for electronic content, tools, and technologies to be accessible. It includes an overview of low vision and describes specific user needs. Additional information...

Introduction:

Accessibility Requirements for People with Low Vision describes what people with low vision need for electronic content, tools, and technologies to be accessible. It includes an overview of low vision and describes specific user needs. It does not set priorities on issues.

User needs can be met at several levels, including hardware, operating systems, user agents (such as web browsers), extensions, plug-ins, assistive technologies, and content. This document does not specify responsibility for meeting user needs, and it does not set technical requirements.

This document is intended to provide the background for developing guidance on making content, tools, and technologies accessible to people with low vision.

Additional details....

**Comment by shawna-slh** [comment]
RESOLUTION 10 Feb telecon https://www.w3.org/2016/02/10-lvtf-minutes.html#item02

**Pull request closed without merging**
