### PR TITLE
Change to scope and definition

### PR DESCRIPTION
**Pull request by WayneEDick**
The undefined concept of luminance is replaced with brightness. It is too complex to introduce here.

### CODE REVIEW

**Comment by awkawk** [comment]
Should be "bright light makes" (not make)

**Comment by shawna-slh** [comment]
A few points:
- We can't say "many" unless we can justify it. It is safer to say "some".
- I don't think we need the qualifier "with low vision". 
- I think we can tighten up the text a bit.
- Is "computer screen with a light background" and "They need to change the background" clear enough that it means the background of the software, not the physical screen?
- I totally agree that we don't want to define or explain in detail "luminance". However, we might want to introduce it in this section, since we use it later in the document – or not. :) Under 3.1 http://w3c.github.io/low-vision-a11y-tf/requirements.html#luminance-and-color we could just change the second sentence to "Related information is in the Light Sensitivity section above."

Edit suggestion:
Some people have extreme sensitivity to light (called photophobia). Bright light makes it difficult or impossible to see, and causes eye pain and headaches. For some people, the normal brightness of a computer screen with a light background is not readable and painful. They need to change the background to a darker color.

**Comment by WayneEDick** [comment]
I put many where there is support. I can insert the referenced.

-----Original Message-----

**Comment by WayneEDick** [comment]
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>Use of Many</title>
</head>
<body>
    <p>The following diseases are associated with photophobia. With abinism, cataracts, glaucoma, RP and toxoplasmosis we have many people with photophobia. Age related macularation is associated with scotoma and of course, age.</p>
    <a href="http://www.tsbvi.edu/eye-conditions">Source (TSBVI)</a>
 <ul>
        <li>Photophobia</li>
        <li>Frequently Associated
            <ul>
                <li>Achromotopsia</li>
                <li>Albinism</li>
                <li>Aniridia</li>
                <li>Buphthalmos</li>
                <li>Cataracts</li>
                <li>Chorioretinitis</li>
                <li>Coloboma</li>
                <li>Corneal Ulcers, Corneal Opacities, Corneal Scarring, Keratitis, and Interstitial Keratitis</li>
                <li>Cortical Visual Impairment (CVI)</li>
                <li>Glaucoma</li>
                <li>Microphthalmia </li>
                <li>Peter’s Anomaly</li>
                <li>Retinitis Pigmentosa (RP)</li>
                <li>Toxopasmosis</li>
                <li>Uveitis</li>
                <li>Wills Tumor</li>
                <li>Sometimes Associated
                    <ul>
                        <li>Keratoconus (KC)</li>
                        <li>Macular Degeneration</li>
                        <li>Scotoma</li>
                    </ul>
                </li>
            </ul>
        </li>

```
</ul>
```

</body>
</html>

**Comment by allanj-uaag** [comment]
I too had concerns with "many", I looked for references/stats, couldn't find any. Generalizations are tough. I am more comfortable with 'some'. having worked with many students over the years as a teacher and at Space Camp, have seen few who are photophobic (extreme light sensitivity). Do the rest have some issues/sensitivities with lighting and glare - yes...so do I.  The list cited by Wayne is long. In my experience student who have had conditions on the Frequently Associated list rarely had "photophobia" as a concomitant condition. That does not mean they didn't have varying issues with lighting and glare, they did, but it wasn't debilitating nor painful. 

+1 to shawn's rewrite.

**Comment by WayneEDick** [comment]
Allen and Shawn,

The reason I use many for photophobia is because:
1. Almost everyone with albinism has it.
2. It is listed among the symptoms of retinitis pigmentosa on the TSBVI
list and the NIH page
3. It is listed as an effect of glaucoma with TSBVI and the NIH.
4. It is listed as a side effect of cataracts with TSBVI.
5. It is a possible side effect of scatoma.
6. It is a side effect of aging, and hence macular degeneration.

That accounts for many people with LV.

Note, many is between some and most. I chose many because it effects many
common causes of LV. I doubt it is most, but it is not infrequent.

I was trying to be accurate. I think some gives the impression that it
might be uncommon, which is definitely not the case.

Wayne

**Comment by WayneEDick** [comment]
+1 to Shawn's edit

**Comment by shawna-slh** [comment]
RESOLUTION 20 Feb telecon https://www.w3.org/2016/02/10-lvtf-minutes.html#item06

**Pull request closed without merging**
