### PR TITLE
Began references.

### PR DESCRIPTION
**Pull request by WayneEDick**
Contrast-LV is for "Most... have multiple impairments..."
Eye-Conditions is for "Many ... photophobia"
I will update this more and more...

### CODE REVIEW

**Comment by WayneEDick** [comment]
24, 25 and 26 are all or none because the href / id matches will fail without the references section.

**Comment by shawna-slh** [comment]
Hi Wayne,

Jim created this page for us to put all the specific references to back up the info in the doc: https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/References

Current draft of the doc includes in the Introduction a bullet:
- <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/References">References</a> provides sources for the information in this document

Probably this issue will be on the agenda next week.

So for now I think it's best to put the references and "justification" in that wiki page, and not in GitHub for the doc. Have you got a wiki user style sheet working OK, or is wiki editing still a royal hassle?

~Shawn

**Comment by WayneEDick** [comment]
We failed to change the some to many in the reference to photophobia. We
don't need a ref to say some.

**Comment by shawna-slh** [comment]
Added to [References](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/References) for now per [RESOLUTION in 17 Feb teleconference](https://www.w3.org/2016/02/17-lvtf-minutes.html#item01)

**Pull request closed without merging**
