### PR TITLE
Update requirements.html

### PR DESCRIPTION
**Pull request by WayneEDick**

### CODE REVIEW

**Comment by WayneEDick** [comment]
This removes a dangling refernece.

**Comment by shawna-slh** [comment]
- Luminance is used in more than just accessibility calculations.
- fyi, some notes on terminology: https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Definitions_of_Low_Vision#Luminance_notes

How about: "Luminance is basically the visual perception of brightness. High luminance is very bright."

**Comment by WayneEDick** [comment]
Luminance is the average brightness across a region. That is, to be
precise, Luminance = brightness / area.

**Comment by shawna-slh** [comment]
After talking it over with Wayne and looking at 3.1 and 3.1.1, tried changing luminance in this pull request:
https://github.com/w3c/low-vision-a11y-tf/pull/22

**Comment by shawna-slh** [comment]
RESOLUTION 10 Feb https://www.w3.org/2016/02/10-lvtf-minutes.html#item08
to accept https://github.com/w3c/low-vision-a11y-tf/pull/22

**Pull request closed without merging**
