### PR TITLE
Separate color from contrast

### PR DESCRIPTION
**Pull request by WayneEDick**
The color example of the original is confusing to me. I give 2. One with grey scale, and one with color.

### CODE REVIEW

**Comment by WayneEDick** [comment]
Many can be justified by
<body>
 <p>Most people with low vision have decreased contrast sensitivity. <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Research">Source (Psychophysics of Reading</a></p>

**Comment by shawna-slh** [comment]
- If we leave "images" in the first sentence, I think we should include the example of text on a background in the sentence. I didn't find a better way to write it without "images".
- I got lost in the examples. :-)
- I don't think we want to say anything like "almost everyone with low vision has low contrast sensitivity" – we don't mention anything like that in the other sections. I thought we might want to mention "Most people lose contrast sensitivity as they age." to show that it is very common – but I see that readers might assume it's only with aging and not other conditions. Maybe leave it out altogether, or maybe something like: "Many people with low vision have low contrast sensitivity, and most people with "normal" vision lose contrast sensitivity as they age."
- How about this for covering the basics:

Contrast sensitivity is the ability to distinguish bright and dim areas of images, for example, to discern text on a background. A common accessibility barrier for people with low contrast sensitivity is gray text on a light background.

Contrast is based on brightness ("luminance"). Colors that look very different (for example, red, blue, green) can have similar brightness, and not provide sufficient contrast. <a href="https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast7.html#visual-audio-contrast7-resources-head">Tools<a/> are available to determine the contrast ratio between colors.

**Comment by WayneEDick** [comment]
+1 to Shawn's edit

**Comment by shawna-slh** [comment]
RESOLUTION 10 Feb https://www.w3.org/2016/02/10-lvtf-minutes.html#item07

**Pull request closed without merging**
