### PR TITLE
Scope and specificity

### PR DESCRIPTION
**Pull request by WayneEDick**
Impairments rarely occur alone. So, this needs to be stated. Multiple impairment is the norm not the exception.
Also, fatigue impacts almost everyone with low vision.

### CODE REVIEW

**Comment by shawna-slh** [comment]
- We can't say "Almost everyone" or "most" unless we have data to back it up. "Some" is safer than "Many" – although maybe "Many" is OK? _[update: Wayne & I talked about providing the sources to back this up -- so we'll work on that.]_
- I like using the specific example of macular degeneration. Below is a suggestion to simplify it:

"Most people with low vision have multiple visual impairments. For example, people with macular degeneration usually develop central field loss ("blind spots"), poor visual acuity, low contrast sensitivity, and high light sensitivity."

**Comment by WayneEDick** [comment]
Actually we can justify this from our definition. Low vision is defined by loss of visual acuity or field loss. In the Legge contrast experiment 16 out of 19 all with acuity loss had low contrast sensitivity. Loss of visual acuity is almost always associated with field loss, photophobia or low contrast sensitivity.. Field loss without visual acuity loss is usually accompanied by photophobia, night blindness (another litght sensivity) or contrast sensitivity.  Most is easily justified.but almost everyone is a little strong since we are including correctable farsightedness and nearsightedness. References: TSBVI and Psychophysics of Reading..

**Comment by WayneEDick** [comment]
Shawn,
We have a strong many for photophobia, contrast sensivity and more than one.
Actually, more than one is more than many it is most, and by a lot! We need
to say that because our 4 impairments really are more like 15. That is a
lot of required flexibility.
Wayne

**Comment by WayneEDick** [comment]
+1 to Shawn's edit

**Comment by mraccess77** [comment]
"Many" sounds goods to me.

**Comment by mraccess77** [comment]
In this case since we have data to back it up - most is fine with me.  In cases where we don't have data then "many" is better.

**Comment by shawna-slh** [comment]
RESOLUTION 10 Feb telecon https://www.w3.org/2016/02/10-lvtf-minutes.html#item05

**Pull request closed without merging**
