### PR TITLE
Legibility, Readability, Visibility [was: Factual Correction]

### PR DESCRIPTION
**Pull request by WayneEDick**
Readability and legibility are different things. This explains the distinction.

### CODE REVIEW

**Comment by WayneEDick** [comment]
The difference between visible (acuity limit) and legible is document many places. That is why there are two measures: (1) Acuity Limit - the smallest size where text can be recognized and (2) Critical print size (CPS) the small est size where someone can read at optimum speed and accuracy. Readability is different again. The hierarchy is this. Visible is necessary for legible. Legible is necessary for readable. The trick is getting to legible in a way that preserves readable.

**Comment by shawna-slh** [comment]
This requires more work. Wayne and I are eager to work together on it, but haven't gotten to it yet...

**Comment by shawna-slh** [comment]
RESOLUTION 10 Feb telecon https://www.w3.org/2016/02/10-lvtf-minutes.html#item09
Leave this open and add a Note in the FPWD.

**Comment by shawna-slh** [comment]
Research and notes are being collected at: https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Research#Legibility_and_Readability_and_.3F.3F.3F

**Comment by shawna-slh** [comment]
superseded by isssue https://github.com/w3c/low-vision-a11y-tf/issues/37

**Pull request closed without merging**
