### PR TITLE
suggestion for 2.1 Scope

### PR DESCRIPTION
**Pull request by AndrewArch**
The term "vision impaired" is commonly used in Australia

### CODE REVIEW

**Comment by shawna-slh** [comment]
In many contexts, "visual impairment" is used to include **both** blind and low vision. We want to distinguish low vision here.

Andrew - does “vision impaired” in Australia include blind, or distinct from blind?

In any case, “vision impaired”  seems very close to "visual impairment" and I'm concerned that adding it would cause more confusion for most people than it would help some people...

[related info: "In the UK, the Certificate of Vision Impairment (CVI) is used to certify patients as severely sight impaired or sight impaired."]

**Comment by AndrewArch** [comment]
Good question Shawn - I'll do some checking

Andrew

On Thursday, 7 April 2016, shawn_slh notifications@github.com wrote:

> In many contexts, "visual impairment" is used to include _both_ blind and
> low vision. We want to distinguish low vision here.
> 
> Andrew - does “vision impaired” in Australia include blind, or distinct
> from blind?
> 
> In any case, “vision impaired” seems very close to "visual impairment" and
> I'm concerned that adding it would cause more confusion for most people
> than it would help some people...
> 
> [related info: "In the UK, the Certificate of Vision Impairment (CVI) is
> used to certify patients as severely sight impaired or sight impaired."]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/pull/48#issuecomment-206452734

## 

"You have to take on challenges to experience living."
Boris von Engelbrechten

**Comment by AndrewArch** [comment]
Hi Shawn,

Some checking with the community here and 'vision impairment' is commonly
taken to mean both compete blindness _and_ the broader range of low vision
issues. So, yes, my suggestion would probably add to the confusion and
should be ignored.

Andrew

---

Andrew Arch

Accessibility & Inclusivity Lead

Digital Transformation Office http://www.dto.gov.au/

p. 0428 134 529

e. andrew.arch@digital.gov.au
t. @AusDTO https://twitter.com/AusDTO  |  @amja https://twitter.com/amja

**Comment by shawna-slh** [comment]
Thanks for following up, Andrew. :-)

**Pull request closed without merging**
